name: Sync Labels

on:
  label:
    types: [created, edited, deleted]
  push:
    branches:
      - master

jobs:
  label-sync:
    name: Install & Run
    runs-on: ubuntu-latest
    env:
      # Personal access token for `hyphacoop-bot` with `repo` permission
      # See: https://github.com/hyphacoop/organizing/settings/secrets/new
      GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
      LABEL_REPO_SOURCE: hyphacoop/organizing
      # Note: `hyphacoop-bot` user must also be given `write` access to repos via @hyphacoop/robots team.
      # See: https://github.com/orgs/hyphacoop/teams/robots/repositories
      # See: https://yaml-multiline.info/
      LABEL_REPO_TARGETS: >-
        hyphacoop/demo-repo
        hyphacoop/handbook
        hyphacoop/hypha.coop
        hyphacoop/hyphacoop-chatbot
        hyphacoop/organizing-private
        hyphacoop/spreadsheet2shortlinks
        hyphacoop/test-private
        hyphacoop/vision.hypha.coop
        hyphacoop/worker-coop-scripts
    steps:
      - name: Setup PHP
        # See: https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.3'
      # See: https://github.com/vanilla/github-sync
      - run: |
          composer require vanilla/github-sync
          for target in $LABEL_REPO_TARGETS; do
            # NOTE: "prune" ensures that missing tags will be culled from target repo, but ONLY if they are unused.
            ./vendor/bin/github-sync labels --from $LABEL_REPO_SOURCE --to $target --delete prune
          done
